version: "3"

services:
  jobmanager:
    # build: .
    image: flink
    container_name: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9091
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./jobs/job.sql:/opt/flink/job.sql

  taskmanager:
    # build: .
    image: flink
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporters: prom
        metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
        metrics.reporter.prom.port: 9091
    depends_on:
      - jobmanager
    command: taskmanager
    deploy:
          replicas: 2

networks:
  data-net:
    external: true
